### ISSUE TITLE
Typographical baselines

### ISSUE THREAD

**Issue by stereobooster** [styled-components/polished#171]
Code https://github.com/michaeltaranto/basekick
Video https://www.youtube.com/watch?v=TGHbkTGVqoU

Related:

- http://compass-style.org/reference/compass/typography/vertical_rhythm/
- http://type-scale.com/
- http://foundation.zurb.com/sites/docs/typography-base.html
- https://github.com/hiulit/Sassy-Gridlover ([demo](https://www.gridlover.net/))
- http://codepen.io/getflourish/full/vXqewy/
- https://github.com/mrmartineau/design-system-utils
- https://github.com/ceteio/styled-components-rhythm

**Comment by bhough** [comment]
Thanks for the feature request @stereobooster. This is one we originally had on our list for V1 but the way it needs to work with global rules gave us pause. As we think about V2, we wouldn't be opposed to revisit this. Any thoughts on what a mixin for this would look like?

**Comment by stereobooster** [comment]
This is not final vision, trying to brainstorm this.

I suppose there is should be "theme" object, like state in redux. For vertical rhythm we need `base font size` and `scale factor` (at least).

### Basic vertical rhythm 

```js
const theme = {
  base_font_size: "16px",
  scale_factor: 1.68
}
font(theme, 0) //paragraph
font(theme, 1) //min heading, for example H3
font(theme, 3) //max heading, for example H1
```

### Gutenberg

[Gutenberg](http://matejlatin.github.io/Gutenberg/) uses `base_font_size` to fit images in grid.

### Adaptive Modular Scale

[Adaptive Modular Scale](http://codepen.io/getflourish/full/vXqewy/) will need following theme object

```js
const theme = {
min: {
  width: 320,
  base_font_size: "16px",
  contrast: 1.2 // the same as scale factor, I suppose
},
max: {
  width: 960,
  base_font_size: "18px",
  contrast: 1.6 // the same as scale factor, I suppose
}}
```

This reminds me about breakpoints, which probably also should be present in theme object.

### Breakpoints

```js
const theme = {
breakpoints: {
  min: 320,
  max: 960
},
base_font_size: "16px", // values at root level are defaults or min breakpoint (mobile first)
contrast: 1.2,
breakpoint_max: {
  base_font_size: "18px",
  contrast: 1.6 // the same as scale factor, I suppose
}}
```

### [Basekick](https://github.com/michaeltaranto/basekick)

```js
theme = {
  typeSizeModifier: 1,
  typeRowSpan: 1,
  descenderHeightScale: 1,
  baseFontSize: 1,
  gridRowHeight: 1,
  lineHeightOverride: 1
}
```

Some of Basekick settings are font family dependent. So we can have database with those values based on font family: `typographicBaselineFor("Roboto")` (in separate repo).

### Bonus points

We also can implement `verticalGrid(theme)`, which will generate styles for grid overlay.

Having this functionality as JavaScript function (instead of css/sass/less) it is easy to implement preview page, like [Adaptive Modular Scale](http://codepen.io/getflourish/full/vXqewy/) or [font-style-matcher](https://meowni.ca/font-style-matcher/).

**Comment by stereobooster** [comment]
This is something similar https://github.com/kyleshevlin/shevyjs

**Comment by oyeanuj** [comment]
Also, being able to set global fluid typography using the popular SASS mixins (https://css-tricks.com/snippets/css/fluid-typography/) would be super helpful!

**Comment by loganpowell** [comment]
Have these issues been addressed in polished as of yet?

**Comment by bhough** [comment]
@loganpowell as of now though. We are still not sold on adding a module to `polished` that relies on global values/styles. It breaks the paradigm of a component being shippable on it's own. While we understand that is a reality of how things work, it is harder to design for and properly communicate to a user of the library.

**Comment by stereobooster** [comment]
https://github.com/rafaelrinaldi/responsive-styles

```js
const breaks = [48, 64, 80]
const r = (props, values) => responsiveStyles(props, values, breaks)

const styles = StyleSheet.create({
  // A la functional CSS
  padding: r('padding', [8, 24, 48]),
  fontSize: r('fontSize', [16, 24, 36]),

  // Combine multiple definitions into a single class name
  colors: combineSameKeys(
    r('color', ['#FFF', '#005782', '#820005', '#16160B']),
    r('backgroundColor', ['#FF0066', '#27D88E', '#FFF5C3', '#E1E1E1'])
  )
})
```

**Comment by bhough** [comment]
between (https://polished.js.org/docs/#between) and fluidRange ( can now be used to scale `font-size` or any other property using linear interpolation. Either of these should be able to be combined with theming to accomplish most of this functionality now with v2.

**Comment by AWR14** [comment]
@bhough came across this when wanting to the mixin in this article https://css-tricks.com/snippets/css/fluid-typography/ and use it in styled-components.

I've tried both between and fluidrange, seem to need different values but both work fine. Was just wondering which one is recommended over the other?

**Comment by bhough** [comment]
@AWR14 it depends on your surrounding code. The only real difference between the two are the media query constraints. In most cases, you will want `fluidRange` as it includes the "stops" at either end of the range. `between` returns just the linear interpolation for the value for cases in which you are handling the media query separately.

**Comment by AWR14** [comment]
@bhough Thanks, i'm going with fluidRange based on your answer. I'm new to styled components and moving over from SCSS, is this the recommended way of adding SCSS Mixin style functions?

**Comment by bhough** [comment]
@AWR14 generally speaking, yes we created these "officially" to ease the transition from SCSS to styled-components.

**Comment by AWR14** [comment]
@bhough Thanks. does it only work with px units? i've set my base font to 10px {font-size: 62.5%;) but gives weird results when using fluidRange 

`${fluidRange(
     {
       prop: 'font-size',
       fromSize: '2rem',
       toSize: '10rem',
     }
   )};`

**Comment by bhough** [comment]
@AWR14 What results are you seeing?

**Comment by AWR14** [comment]
@bhough it appears to not be as smooth when using rem, seems to jump in size more.

```
`${fluidRange(
     {
       prop: 'font-size',
       fromSize: '40px',
       toSize: '100px',
     },
     '300px',
     '1200px',
   )};`

```

```
${fluidRange(
     {
       prop: 'font-size',
       fromSize: '40px',
       toSize: '100px',
     },
     '300px',
     '1200px',
   )};
```

i am doing this to set the default to 10px

```
html {
    font-size: 62.5%;
}
```
