### ISSUE TITLE
Unknown duplicated console warnings

### ISSUE THREAD

**Issue by AnassZaki** [styled-components/polished#521]
### Question
Hello! I'm using `"polished": "^3.4.4"`, when running my project I get a lot of these messages in the console, I am using the `stripUnit` function, any idea why? 
![image](https://user-images.githubusercontent.com/14060253/85839266-ffa3e880-b79a-11ea-9011-b057a9ff3120.png)

## Relevant Information
Sample code:
![image](https://user-images.githubusercontent.com/14060253/85839591-69bc8d80-b79b-11ea-8763-85994047c314.png)

**Comment by bhough** [comment]
@AnassZaki You need to upgrade your version of polished. This issue was addressed in `3.5.1` (https://github.com/styled-components/polished/releases/tag/v3.5.1) and the latest is `3.6.5`.

**Comment by AnassZaki** [comment]
@bhough Even though I upgraded the package, I still get the messages on the console.

**Comment by bhough** [comment]
@AnassZaki Assuming that sample code above is yours, you are getting the message still because you are using deprecated functionality. You want to be using `getValueAndUnit`https://polished.js.org/docs/#getvalueandunit. We are deprecating returning the unit from `stripUnit`.

**Comment by AnassZaki** [comment]
@bhough It is not my code, could you please show me how to use the `getValueAndUnit` in this case?

**Comment by bhough** [comment]
@AnassZaki You should be able to simply replace `stripUnit` with `getValueAndUnit` and it will work exactly the same. Only difference is you only need to pass the value and it will return the same array.

```javascript
const fromSizeUnit = getValueAndUnit(from)[1];
const toSizeUnit = getValueAndUnit(to)[1];
```
